# Generated by Django 6.0.5 on 2026-05-19 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=14, unique=True)),
                ('category', models.CharField(choices=[('cyberstalking', 'Cyberstalking & Harassment'), ('doxing', 'Non-Consensual Image Sharing / DoXing'), ('impersonation', 'Impersonation & Identity Theft'), ('threats', 'Online Threats & Hate Speech'), ('other', 'Other Forms of Online Abuse')], max_length=30)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('platform_used', models.CharField(help_text='e.g., WhatsApp, X, Facebook, Email', max_length=100)),
                ('evidence_attachment', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ai_classified_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_urgency_score', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical Intervention Required')], default='low', max_length=20)),
                ('ai_research_insights', models.TextField(blank=True, help_text='AI generated pattern matching and trend cross-referencing.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Investigation'), ('action_taken', 'Action Taken / Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter_profile', models.ForeignKey(blank=True, help_text='Optional link to authenticated user profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
