# Generated by Django 6.0.5 on 2026-06-30 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrensHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(choices=[('superadmin', 'Super Admin - Full System Access'), ('admin', 'Admin - Department Management'), ('assistant_admin', 'Assistant Admin - Report Management'), ('department_lead', 'Department Lead - Department-Specific Access')], default='admin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
                ('manages_departments', models.ManyToManyField(blank=True, related_name='admin_managers', to='reports.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=14, unique=True)),
                ('case_access_pin', models.CharField(editable=False, max_length=6)),
                ('incident_category', models.CharField(choices=[('cyberstalking', 'Cyberstalking & Harassment'), ('doxing', 'Non-Consensual Image Sharing / DoXing'), ('impersonation', 'Impersonation & Identity Theft'), ('threats', 'Online Threats & Hate Speech'), ('other', 'Other Forms of Online Abuse'), ('children_home_support', "Children's Home Support")], max_length=100)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('platform_used', models.CharField(max_length=100)),
                ('evidence_attachment', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('level', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Initial Review'), (2, 'Escalated/Urgent'), (3, 'Resolved')], default=0)),
                ('reporter_type', models.CharField(default='self', max_length=20)),
                ('id_type', models.CharField(default='National ID', max_length=50)),
                ('national_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_mode', models.CharField(default='Phone Number', max_length=50)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('report_police', models.BooleanField(default=False)),
                ('recommend_counseling', models.BooleanField(default=False)),
                ('consent_investigation', models.BooleanField(default=False)),
                ('allow_contact', models.BooleanField(default=False)),
                ('gender', models.CharField(default='P', max_length=20)),
                ('age_group', models.CharField(blank=True, max_length=10, null=True)),
                ('disability', models.CharField(default='none', max_length=50)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_classified_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_urgency_score', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical Intervention Required')], default='low', max_length=20)),
                ('ai_research_insights', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Investigation'), ('action_taken', 'Action Taken / Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.department')),
                ('assigned_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.childrenshome')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('reporter_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reports.incidentreport')),
            ],
        ),
    ]
