# Generated by Django 6.0.5 on 2026-05-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_phone',
            field=models.CharField(blank=True, help_text='Optional contact number for alerts.', max_length=20, null=True),
        ),
    ]
