# Generated by Django 6.0.5 on 2026-05-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_incidentreport_reporter_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='category',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='age_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='allow_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='case_access_pin',
            field=models.CharField(default='000000', editable=False, help_text='Secure one-time viewer access pin.', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='disability',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='gender',
            field=models.CharField(default='P', max_length=5),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_category',
            field=models.CharField(choices=[('cyberstalking', 'Cyberstalking & Harassment'), ('doxing', 'Non-Consensual Image Sharing / DoXing'), ('impersonation', 'Impersonation & Identity Theft'), ('threats', 'Online Threats & Hate Speech'), ('other', 'Other Forms of Online Abuse')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_type',
            field=models.CharField(default='self', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
