# Generated by Django 6.0.5 on 2026-05-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_department_incidentreport_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='childrenshome',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='childrenshome',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='childrenshome',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='assigned_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.childrenshome'),
        ),
        migrations.AlterField(
            model_name='childrenshome',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='case_access_pin',
            field=models.CharField(editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_category',
            field=models.CharField(choices=[('cyberstalking', 'Cyberstalking & Harassment'), ('doxing', 'Non-Consensual Image Sharing / DoXing'), ('impersonation', 'Impersonation & Identity Theft'), ('threats', 'Online Threats & Hate Speech'), ('other', 'Other Forms of Online Abuse'), ('children_home_support', "Children's Home Support")], max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='platform_used',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reporter_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
