# Generated by Django 6.0.5 on 2026-05-23 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('case_access_pin', models.CharField(editable=False, max_length=12)),
                ('reporter_type', models.CharField(choices=[('self', 'Reporting for Myself'), ('victim_adult', 'Reporting on behalf of another Adult'), ('child', 'Reporting on behalf of a Minor/Child')], default='self', max_length=15)),
                ('allow_contact', models.BooleanField(default=False, help_text='Can our care teams reach back out to you?')),
                ('contact_detail', models.CharField(blank=True, help_text='WhatsApp / Email / Phone link string', max_length=150, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('O', 'Other'), ('P', 'Prefer not to say')], default='P', max_length=5)),
                ('age_group', models.CharField(choices=[('U18', 'Under 18 years'), ('18-24', '18 - 24 years'), ('25-34', '25 - 34 years'), ('35-44', '35 - 44 years'), ('45+', '45 years and above')], max_length=10)),
                ('disability', models.CharField(choices=[('none', 'No disability condition'), ('visual', 'Visual impairment'), ('hearing', 'Hearing impairment'), ('mobility', 'Physical/Mobility impairment'), ('cognitive', 'Cognitive/Intellectual impairment'), ('other', 'Other constraint variants')], default='none', max_length=20)),
                ('incident_category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_child_directed', models.BooleanField(default=False, editable=False)),
                ('severity', models.CharField(choices=[('LOW', 'Low Risk - Routine Monitoring'), ('MEDIUM', 'Medium Risk - Administrative Action Required'), ('HIGH', 'High Risk - Immediate Legal/Medical Intervention'), ('CRITICAL', 'Critical Crisis - Law Enforcement Dispatch')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted & Triaging'), ('In_Review', 'Under Review'), ('Assigned', 'Routed to Specialist'), ('Action_Taken', 'Intervention Complete'), ('Closed', 'Archived Secured')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='auth.group')),
            ],
        ),
    ]
